function hideElements() {
    const wordsToHide = [
		// Negative Abusive Violent wordsToHide
		'abuse',
		'abused',
		'abusing',
		'agony',
		'agonizing',
		'ambush',
		'ambushed',
		'amputate',
		'amputated',
		'assault',
		'assaulted',
		'assaulting',
		'attacked',
		'attacker',
		'attackers',
		'attacking',
		'attacks',
		'barbaric',
		'beaten',
		'beating',
		'beaten\u2019s',
		"beaten's",
		'behead',
		'beheaded',
		'bleeding',
		'bleeds',
		'blood',
		'bloodied',
		'bloodshed',
		'bloody',
		'bombed',
		'bomber',
		'bombing',
		'bombings',
		'brawl',
		'brawling',
		'bruised',
		'bruising',
		'brutality',
		'brutal',
		'burn',
		'burned',
		'burning',
		'burns',
		'butcher',
		'butchered',
		'cadaver',
		'casualty',
		'casualties',
		'choke',
		'choked',
		'choking',
		'collapse',
		'collapsed',
		'collapsing',
		'combat',
		'combating',
		'conflict',
		'corpse',
		'corpses',
		'crashed',
		'crashes',
		'crashing',
		'crucify',
		'crucified',
		'crushed',
		'crushing',
		'cut',
		'cutting',
		'damaged',
		'damages',
		'damaging',
	    	'dead',
		'deadly',
		'decapitate',
		'decapitated',
		'deceased',
		'decompose',
		'decomposed',
		'demise',
		'demolish',
		'demolished',
		'destroy',
		'destroyed',
		'destroying',
		'destroys',
		'detonate',
		'detonated',
		'dismember',
		'dismembered',
		'drown',
		'drowned',
		'drowning',
		'electrocute',
		'electrocuted',
		'eliminate',
		'eliminated',
		'eliminating',
		'execute',
		'executed',
		'executing',
		'execution',
		'explode',
		'exploded',
		'explosion',
		'fatal',
		'fatality',
		'fell',
		'falling',
		'falls',
		'fight',
		'fighting',
		'fights',
		'forceful',
		'fought',
		'fracture',
		'fractured',
		'gash',
		'gashed',
		'gashing',
		'gore',
		'gored',
		'goring',
		'gunfire',
		'gunshot',
		'gunshots',
		'harm',
		'harmed',
		'harming',
		'harms',
		'hemorrhage',
		'hit',
		'hitting',
		'hits',
		'horrific',
		'horror',
		'hurt',
		'hurting',
		'hurts',
		'impale',
		'impaled',
		'incinerate',
		'incinerated',
		'infected',
		'infection',
		'injure',
		'injured',
		'injuring',
		'injuries',
		'injury',
		'kidnap',
		'kidnapped',
		'kidnapping',
		'kill',
		'killed',
		'killer',
		'killing',
		'kills',
		'lacerate',
		'lacerated',
		'lethal',
		'maim',
		'maimed',
		'maiming',
		'malicious',
		'massacre',
		'massacred',
		'mangled',
		'mangling',
		'murder',
		'murdered',
		'murderer',
		'murderous',
		'mutilate',
		'mutilated',
		'paralyze',
		'paralyzed',
		'perish',
		'perished',
		'perishing',
		'poison',
		'poisoned',
		'poisoning',
		'pummel',
		'pummeled',
		'punish',
		'punished',
		'rape',
		'raped',
		'raping',
		'ravage',
		'ravaged',
		'rip',
		'ripped',
		'ripping',
		'rupture',
		'ruptured',
		'savage',
		'savaged',
		'scald',
		'scalded',
		'sever',
		'severed',
		'shot',
		'shooting',
		'shots',
		'shred',
		'shredded',
		'slain',
		'slaughter',
		'slaughtered',
		'slay',
		'slaying',
		'slash',
		'slashed',
		'slashing',
		'slit',
		'smash',
		'smashed',
		'smashing',
		'smother',
		'smothered',
		'stab',
		'stabbed',
		'stabbing',
		'strangle',
		'strangled',
		'strangling',
		'struck',
		'striking',
		'suffer',
		'suffered',
		'suffering',
		'suffers',
		'suffocate',
		'suffocated',
		'suicide',
		'terrorize',
		'terrorized',
		'torture',
		'tortured',
		'torturing',
		'trauma',
		'traumatic',
		'trample',
		'trampled',
		'vanish',
		'vanished',
		'vanishing',
		'victim',
		'victims',
		'violence',
		'violent',
		'violently',
		'wound',
		'wounded',
		'wounding',
		'wounds',
		'wreck',
		'wrecked',
		'wrecking',
        // Presidential/Political variations
        'president',
        'presidents',
        'president\u2019s',
        "president's",
        'presidential',
        'presidency',
        'presidencies',
        'pres.',
        'pres',
        'potus',
        'flotus',
        'commander in chief',
        'commander-in-chief',
        'oval office',
        'executive branch',
        'white house',
        'whitehouse',
        'administration',
        'chief executive',
        'head of state',
        'head of government',
        'mr president',
        'mr. president',
        'madam president',
        'madame president',
        'former president',
        'ex president',
        'ex-president',
        'vice president',
        'vice-president',
        'vp',
        'v.p.',
        'veep',

        // Trump variations
        'trump',
        'donald',
        'trumpism',
        'trumpian',
        'trumper',
        'trumpers',
        'trumpiest',
        'trumping',
        'trumped',
        'donald trump',
        'donald j trump',
        'donald j. trump',
        'donald john trump',
        'd. trump',
        'd.j. trump',
        'djt',
        'donaldtrump',
        'realdonaldtrump',
        'president trump',
        'mr trump',
        'mr. trump',
        'don trump',
        'donnie',
        'trumpworld',
        'trumpverse',
        'trump\u2019s',
        "trump's",
        'trump jr',
        'trump junior',
        'trump j.r.',
        'trump sr',
        'trump senior',
        '45th',
        '45',
        '#45',

        // Expanded Elon/Musk variations
        'elon',
        'musk',
        'elon musk',
        'elonmusk',
        '@elonmusk',
        'e musk',
        'e. musk',
        'mr musk',
        'mr. musk',
        'musk\u2019s',
        "musk's",
        'musks',
        'musky',
        'elongated',
        'elonated',
        'technoking',
        'space karen',
        'rocket man',
        'rocketman',
        'rocket boy',
        'apartheid clyde',
        'tech bro',
        'techbro',
        'iron man',
        'ironman',
        'real iron man',
        'real ironman',
        'real life iron man',
        'real-life iron man',
        'space x guy',
        'spacex guy',
        'tesla guy',
        'twitter guy',
        'x guy',
        'dogefather',
        'doge father',
        'e. r. musk',
        'elon reeve musk',
        'muskian',
        'musked',
        'musking',
        'elonverse',
        'muskverse',
        'muskism',
        'elongate',
        'elonjet',
        'elon jet',
        '@elonjet',
        'tesla ceo',
        'tesla chief',
        'tesla founder',
        'tesla owner',
        'tesla head',
        'tesla boss',
        'spacex ceo',
        'spacex chief',
        'spacex founder',
        'spacex owner',
        'spacex head',
        'spacex boss',
        'twitter ceo',
        'twitter chief',
        'twitter owner',
        'twitter head',
        'twitter boss',
        'x ceo',
        'x chief',
        'x owner',
        'x head',
        'x boss',
        'boring company',
        'boring co',
        'neuralink',
        'openai founder',
        'paypal founder',
        'x.com',
        'xai',
        'x ai',
        'chief twit',
        'former twitter',
        'ex twitter',
        'ex-twitter',
        'space karen',
        'technoking',
        'emerald boy',
        'union buster',
        'market manipulator',
        'meme lord',
        'memelord',
        'musk rat',
        'muskrat',
        'edgelord',
        'edge lord',
        'rocket jesus',
        'space jesus',
        'tech jesus',
        'musky husky',
        'elongated muskrat',
        'emerald prince',
        'mars guy',
        'mars man',
        'starship guy',
        'pretend engineer',
        'african american',
        'south african',
        'pretoria boy',
        'richest man',
        'richest person',
        'wealthiest man',
        'wealthiest person',
        'worlds richest',
        "world's richest",
        'world richest',
        'billionaire boss',
        'billionaire ceo',
        'billionaire owner',
        'tech billionaire',
        'tesla billionaire',
        'space billionaire',
        '@elonmusk',
        '@elonmusks',
        '@realelon',
        '@realelonmusk',
        '@tesla_ceo',
        '@spacex_ceo',
        '@xai_ceo',
        '@boringcompany',
        '@x_ceo',
        '@musk',
        '@e_musk',
        '@themusk',
        '@elonofficial',
        'musk says',
        'musk said',
        'musk tweets',
        'musk tweeted',
        'musk posts',
        'musk posted',
        'musk announces',
        'musk announced',
        'musk claims',
        'musk claimed',
        'according to musk',
        'according to elon',
        'per elon',
        'per musk',

        // Combined context terms
        'tesla chief',
        'tesla boss',
        'spacex chief',
        'spacex boss',
        'twitter chief',
        'twitter boss',
        'x chief',
        'x boss',
        'mar-a-lago',
        'maralago',
        'maga',
        'magaa',
        'make america great',
        '45th president',
        'former president',
        'presidential election',
        'presidential campaign',
        'presidential candidate',
        'presidential race',
        'presidential bid',
        'presidential run',
        'presidential nominee',
        'presidential hopeful',
        'running for president',
        'republican nominee',
        'democratic nominee',
        'gop nominee',
        'republican candidate',
        'democratic candidate',
        'gop candidate',
        
        // Handle common misspellings
        'trumph',
        'trmp',
        'trmup',
        'drumpf',
        'drumph',
        'elan',
        'elong',
        'elonge',
        'elan mask',
        'elon mask',
        'elon must',
        'elon musket',
        'elon mosque',
        'eelon',
        'ilon',
        'elonn',
        'musc',
        'mosk',
        'mousk',
        'mussk',
        'musque',
        'elun',
        'eloln',
        'alon',
        'eyon',
        'elon/musk',
        'e/musk',
        'musk/elon',
        'mr.musk',
        'mr.elon',
        'sir elon',
        'lord elon',
        'papa elon',
        'daddy elon',
        'doneld',
        'donnald',
        'donal',
        'president',
        'precedent',
        'presidant',
        'preident',
        'presedent',
        'preisdent'
    ];

    const pattern = wordsToHide
        .map(word => {
            const escaped = word.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
            return word.startsWith('@') || word.startsWith('#') || word.includes('-') ? escaped : `\\b${escaped}\\b`;
        })
        .join('|');
    const regex = new RegExp(pattern, 'gi');

    const walker = document.createTreeWalker(
        document.body,
        NodeFilter.SHOW_TEXT,
        null,
        false
    );

    let node;
    while (node = walker.nextNode()) {
        if (node.parentElement.style.display === 'none' ||
            node.parentElement.tagName.toLowerCase() === 'script' ||
            node.parentElement.tagName.toLowerCase() === 'style' ||
            node.parentElement.tagName.toLowerCase() === 'noscript') {
            continue;
        }

        if (regex.test(node.textContent)) {
            let container = node.parentElement;
            
            if (container.childNodes.length <= 3) {
                container.style.display = 'none';
            } else {
                const text = node.textContent;
                const newHtml = text.replace(regex, '<span style="display: none;">$&</span>');
                
                const temp = document.createElement('span');
                temp.innerHTML = newHtml;
                
                node.parentNode.replaceChild(temp, node);
            }
        }
    }
}

document.addEventListener('DOMContentLoaded', hideElements);
setTimeout(hideElements, 1000);

const observer = new MutationObserver((mutations) => {
    mutations.forEach(mutation => {
        if (!mutation.target.isContentEditable) {
            hideElements();
        }
    });
});

observer.observe(document.body, {
    childList: true,
    subtree: true,
    characterData: true
});
