const wordsToHide = [
		// Negative Abusive Violent wordsToHide
		'abuse',
		'abused',
		'abusing',
		'agony',
		'agonizing',
		'ambush',
		'ambushed',
		'amputate',
		'amputated',
		'assault',
		'assaulted',
		'assaulting',
		'attacked',
		'attacker',
		'attackers',
		'attacking',
		'attacks',
		'barbaric',
		'beaten',
		'beating',
		'beaten\u2019s',
		"beaten's",
		'behead',
		'beheaded',
		'bleeding',
		'bleeds',
		'blood',
		'bloodied',
		'bloodshed',
		'bloody',
		'bombed',
		'bomber',
		'bombing',
		'bombings',
		'brawl',
		'brawling',
		'bruised',
		'bruising',
		'brutality',
		'brutal',
		'brutally',
		'burn',
		'burned',
		'burning',
		'burns',
		'butcher',
		'butchering',
		'butchered',
		'cadaver',
		'casualty',
		'casualties',
		'choke',
		'choked',
		'choking',
		'collapse',
		'collapsed',
		'collapsing',
		'combat',
		'combating',
		'conflict',
		'conflicts',
		'corpse',
		'corpses',
		'crash',
		'crashed',
		'crashes',
		'crashing',
		'crucify',
		'crucified',
		'crushed',
		'crushing',
		'cutting',
		'dead',
		'deadly',
		'decapitate',
		'decapitated',
		'deceased',
		'decompose',
		'decomposed',
		'demise',
		'demolish',
		'demolished',
		'destroy',
		'destroyed',
		'destroying',
		'destroys',
		'detonate',
		'detonated',
		'dismember',
		'dismembered',
		'drown',
		'drowned',
		'drowning',
		'electrocute',
		'electrocuted',
		'execute',
		'executed',
		'executing',
		'execution',
		'explode',
		'exploded',
		'explosion',
		'fatal',
		'fatality',
		'fight',
		'fighting',
		'fights',
		'gash',
		'gashed',
		'gashing',
		'gore',
		'gored',
		'goring',
		'gunfire',
		'gunshot',
		'gunshots',
		'harm',
		'harmed',
		'harming',
		'harms',
		'hemorrhage',
		'homicide',
		'horrific',
		'horror',
		'hurt',
		'hurting',
		'hurts',
		'impale',
		'impaled',
		'incinerate',
		'incinerated',
		'infected',
		'infection',
		'injure',
		'injured',
		'injuring',
		'injuries',
		'injury',
		'kidnap',
		'kidnapped',
		'kidnapping',
		'kill',
		'killed',
		'killer',
		'killing',
		'kills',
		'lacerate',
		'lacerated',
		'lethal',
		'maim',
		'maimed',
		'maiming',
		'malicious',
		'massacre',
		'massacred',
		'mangled',
		'mangling',
		'murder',
		'murdered',
		'murderer',
		'murderous',
		'mutilate',
		'mutilated',
		'paralyze',
		'paralyzed',
		'perish',
		'perished',
		'perishing',
		'poison',
		'poisoned',
		'poisoning',
		'pummel',
		'pummeled',
		'punish',
		'punished',
		'rape',
		'raped',
		'raping',
		'ravage',
		'ravaged',
		'rip',
		'ripped',
		'ripping',
		'rupture',
		'ruptured',
		'savage',
		'savaged',
		'scald',
		'scalded',
		'sever',
		'severed',
		'shot',
		'shooting',
		'shots',
		'shred',
		'shredded',
		'slain',
		'slaughter',
		'slaughtered',
		'slay',
		'slaying',
		'slash',
		'slashed',
		'slashing',
		'slit',
		'smash',
		'smashed',
		'smashing',
		'smother',
		'smothered',
		'stab',
		'stabbed',
		'stabbing',
		'strangle',
		'strangled',
		'strangling',
		'struck',
		'striking',
		'suffer',
		'suffered',
		'suffering',
		'suffers',
		'suffocate',
		'suffocated',
		'suicide',
		'terrorize',
		'terrorized',
		'torture',
		'tortured',
		'torturing',
		'trauma',
		'traumatic',
		'trample',
		'trampled',
		'vanish',
		'vanished',
		'vanishing',
		'victim',
		'victims',
		'violence',
		'violent',
		'violently',
		'wound',
		'wounded',
		'wounding',
		'wounds',
		'wreck',
		'wrecked',
		'wrecking',
        // Presidential/Political variations
        'president',
        'presidents',
        'president\u2019s',
        "president's",
        'presidential',
        'presidency',
        'presidencies',
        'pres.',
        'pres',
        'potus',
        'flotus',
        'commander in chief',
        'commander-in-chief',
        'oval office',
        'executive branch',
        'white house',
        'whitehouse',
        'administration',
        'chief executive',
        'head of state',
        'head of government',
        'mr president',
        'mr. president',
        'madam president',
        'madame president',
        'former president',
        'ex president',
        'ex-president',
        'vice president',
        'vice-president',
        'vp',
        'v.p.',
        'veep',

        // Trump variations
        'trump',
        'donald',
        'trumpism',
        'trumpian',
        'trumper',
        'trumpers',
        'trumpiest',
        'trumping',
        'trumped',
        'donald trump',
        'donald j trump',
        'donald j. trump',
        'donald john trump',
        'd. trump',
        'd.j. trump',
        'djt',
        'donaldtrump',
        'realdonaldtrump',
        'president trump',
        'mr trump',
        'mr. trump',
        'don trump',
        'donnie',
        'trumpworld',
        'trumpverse',
        'trump\u2019s',
        "trump's",
        'trump jr',
        'trump junior',
        'trump j.r.',
        'trump sr',
        'trump senior',
        '45th',
        '45',
        '#45',

        // Expanded Elon/Musk variations
        'elon',
        'musk',
        'elon musk',
        'elonmusk',
        '@elonmusk',
        'e musk',
        'e. musk',
        'mr musk',
        'mr. musk',
        'musk\u2019s',
        "musk's",
        'musks',
        'musky',
        'elongated',
        'elonated',
        'technoking',
        'space karen',
        'rocket man',
        'rocketman',
        'rocket boy',
        'apartheid clyde',
        'tech bro',
        'techbro',
        'iron man',
        'ironman',
        'real iron man',
        'real ironman',
        'real life iron man',
        'real-life iron man',
        'space x guy',
        'spacex guy',
        'tesla guy',
        'twitter guy',
        'x guy',
        'dogefather',
        'doge father',
        'e. r. musk',
        'elon reeve musk',
        'muskian',
        'musked',
        'musking',
        'elonverse',
        'muskverse',
        'muskism',
        'elongate',
        'elonjet',
        'elon jet',
        '@elonjet',
        'tesla ceo',
        'tesla chief',
        'tesla founder',
        'tesla owner',
        'tesla head',
        'tesla boss',
        'spacex ceo',
        'spacex chief',
        'spacex founder',
        'spacex owner',
        'spacex head',
        'spacex boss',
        'twitter ceo',
        'twitter chief',
        'twitter owner',
        'twitter head',
        'twitter boss',
        'x ceo',
        'x chief',
        'x owner',
        'x head',
        'x boss',
        'boring company',
        'boring co',
        'neuralink',
        'openai founder',
        'paypal founder',
        'x.com',
        'xai',
        'x ai',
        'chief twit',
        'former twitter',
        'ex twitter',
        'ex-twitter',
        'space karen',
        'technoking',
        'emerald boy',
        'union buster',
        'market manipulator',
        'meme lord',
        'memelord',
        'musk rat',
        'muskrat',
        'edgelord',
        'edge lord',
        'rocket jesus',
        'space jesus',
        'tech jesus',
        'musky husky',
        'elongated muskrat',
        'emerald prince',
        'mars guy',
        'mars man',
        'starship guy',
        'pretend engineer',
        'african american',
        'south african',
        'pretoria boy',
        'richest man',
        'richest person',
        'wealthiest man',
        'wealthiest person',
        'worlds richest',
        "world's richest",
        'world richest',
        'billionaire boss',
        'billionaire ceo',
        'billionaire owner',
        'tech billionaire',
        'tesla billionaire',
        'space billionaire',
        '@elonmusk',
        '@elonmusks',
        '@realelon',
        '@realelonmusk',
        '@tesla_ceo',
        '@spacex_ceo',
        '@xai_ceo',
        '@boringcompany',
        '@x_ceo',
        '@musk',
        '@e_musk',
        '@themusk',
        '@elonofficial',
        'musk says',
        'musk said',
        'musk tweets',
        'musk tweeted',
        'musk posts',
        'musk posted',
        'musk announces',
        'musk announced',
        'musk claims',
        'musk claimed',
        'according to musk',
        'according to elon',
        'per elon',
        'per musk',

        // Combined context terms
        'tesla chief',
        'tesla boss',
        'spacex chief',
        'spacex boss',
        'twitter chief',
        'twitter boss',
        'x chief',
        'x boss',
        'mar-a-lago',
        'maralago',
        'maga',
        'magaa',
        'make america great',
        '45th president',
        'former president',
        'presidential election',
        'presidential campaign',
        'presidential candidate',
        'presidential race',
        'presidential bid',
        'presidential run',
        'presidential nominee',
        'presidential hopeful',
        'running for president',
        'republican nominee',
        'democratic nominee',
        'gop nominee',
		'republican',
		'democrat',
        'republican candidate',
        'democratic candidate',
		'dems',
		'dem',
        'gop candidate',

		// Fox news charged words
		'gender-affirming',
		'gender identity',
		'gender ideology',
		'gender indoctrination',
		'transgender agenda',
		'trans agenda',
		'woke agenda',
		'woke ideology',
		'woke capitalism',
		'woke corporation',
		'woke military',
		'woke education',
		'woke indoctrination',
		'corporate wokeness',
		'radical gender theory',
		'gender theory',
		'social engineering',
		'social experimentation',
		'liberal agenda',
		'leftist agenda',
		'socialist agenda',
		'radical agenda',
		'radical left agenda',
		'progressive agenda',
		'globalist agenda',
		'critical race theory',
		'CRT indoctrination',
		'anti-American curriculum',
		'anti-police agenda',
		'defund movement',
		'radical prosecutors',
		'soft-on-crime policies',
		'sanctuary policies',
		'open border policies',
		'border crisis',
		'invasion at the border',
		'migrant surge',
		'illegal alien crime',
		'drug cartels',
		'human trafficking',
		'grooming',
		'child indoctrination',
		'parental rights',
		'war on parents',
		'war on family',
		'war on faith',
		'religious persecution',
		'attack on Christianity',
		'war on Christmas',
		'cancel culture mob',
		'radical mob',
		'liberal mob',
		'leftist mob',
		'anti-police mob',
		'militant activists',
		'radical activists',
		'far-left extremists',
		'antifa violence',
		'BLM riots',
		'radical environmentalism',
		'climate alarmism',
		'climate hysteria',
		'green new disaster',
		'war on fossil fuels',
		'war on energy',
		'energy crisis',
		'Biden gas prices',
		'Bidenflation',
		'socialist spending',
		'radical spending',
		'government takeover',
		'government overreach',
		'nanny state',
		'deep state',
		'shadow government',
		'coastal elites',
		'liberal elites',
		'Hollywood elites',
		'media bias',
		'fake news media',
		'mainstream media lies',
		'Big Tech censorship',
		'conservative censorship',
		'social media purge',
		'election integrity',
		'voter fraud',
		'stolen election',
		'rigged system',
		'radical socialism',
		'marxist ideology',
		'communist threat',
		'radical Islamic',
		'war on police',
		'war on women sports',
		'attack on girls sports',
		'biological males in sports',
		'anti-gun agenda',
		'Second Amendment attack',
		'constitutional rights attack',
		'religious liberty attack',
		'free speech attack',
		'radical judges',
		'activist judges',
		'court packing scheme',
		'radical Supreme Court agenda',
		'war on traditional values',
		'war on merit',
		'assault on excellence',
		'anti-white racism',
		'reverse discrimination',
		'forced diversity',
		'diversity quotas',
		'equity mandate',
		'radical equity agenda',
		'politically correct',
		'liberal propaganda',
		'leftist propaganda',
		'socialist propaganda',
		'marxist propaganda',
		'radical propaganda',
		'culture war attack',
		'war on masculinity',
		'war on boys',
		'war on men',
		'feminist agenda',
		'radical feminist',
		'anti-family agenda',
		'anti-American agenda',
		'patriot persecution',
		'conservative persecution',
		'Christian persecution',
		'liberal bias',
		'left-wing bias',
		'media manipulation',
		'Democrat power grab',
		'radical Democrat',
		'socialist Democrat',
		'far-left Democrat',
		'radical socialist agenda',
		'radical marxist agenda',
		'Biden border crisis',
		'Biden crime crisis',
		'Biden inflation crisis',
		'Biden energy crisis',
		'Biden foreign policy disaster',
		'Biden weakness',
		'Biden cognitive decline',
		'Harris border failure',
		'Squad agenda',
		'AOC socialism',
		'Bernie socialism',
		'Clinton corruption',
		'Obama legacy',
		'Obama policies',
		'Soros-funded',
		'Soros-backed',
		'Gates-funded',
		'climate industrial complex',
		'green energy scam',
		'climate change hoax',
		'COVID overreach',
		'mask mandate tyranny',
		'vaccine mandate',
		'medical freedom',
		'medical tyranny',
		'health freedom',
		'government control',
		'surveillance state',
		'police state',
		'radical bureaucrats',
		'administrative state',
		'educational indoctrination',
		'classroom indoctrination',
		'liberal professor',
		'radical professor',
		'campus radicalism',
		'campus leftism',
		'university bias',
		'academic bias',

		// Conservative-Leaning Media
		'Fox News',
		'Fox News Channel',
		'Fox',
		'Fox Nation',
		'Fox Business',
		'Fox & Friends',
		'Newsmax',
		'NewsMax TV',
		'OANN',
		'One America News Network',
		'One America News',
		'The Blaze',
		'Breitbart',
		'Breitbart News',
		'Daily Wire',
		'Daily Caller',
		'Washington Times',
		'Washington Examiner',
		'New York Post',
		'Post',
		'Red State',
		'Townhall',
		'PragerU',

		// Liberal-Leaning Media
		'CNN',
		'Cable News Network',
		'CNN+',
		'MSNBC',
		'NBC News',
		'CNBC',
		'ABC News',
		'CBS News',
		'PBS',
		'Public Broadcasting Service',
		'NPR',
		'National Public Radio',
		'Huffington Post',
		'HuffPost',
		'Vox',
		'Vox Media',
		'Vice',
		'Vice News',
		'Mother Jones',
		'The Nation',
		'Daily Beast',
		'Slate',
		'Salon',
		'BuzzFeed News',
		'BuzzFeed',

		// Mainstream Print/Digital
		'New York Times',
		'NYT',
		'The Times',
		'Washington Post',
		'WaPo',
		'The Post',
		'USA Today',
		'Wall Street Journal',
		'WSJ',
		'The Journal',
		'Los Angeles Times',
		'LA Times',
		'Chicago Tribune',
		'The Tribune',
		'Boston Globe',
		'The Globe',
		'Associated Press',
		'AP News',
		'Reuters',
		'Bloomberg',
		'Bloomberg News',
		'Politico',
		'The Hill',
		'Roll Call',
		'RealClearPolitics',
		'RCP',
		'Axios',

		// International
		'BBC',
		'British Broadcasting Corporation',
		'BBC News',
		'BBC America',
		'Al Jazeera',
		'Al Jazeera English',
		'AJE',
		'RT',
		'Russia Today',
		'Deutsche Welle',
		'DW News',
		'France 24',
		'Sky News',

		// Common Nicknames/Slang
		'Mainstream Media',
		'MSM',
		'Legacy Media',
		'Corporate Media',
		'State Media',
		'Conservative Media',
		'Right-Wing Media',
		'Liberal Media',
		'Left-Wing Media',
		'Progressive Media',
		'Alternative Media',
		'Independent Media',
		'Fake News',
		'Lamestream Media',
		'Communist News Network', // Derogatory for CNN
		'Faux News', // Derogatory for Fox News
		'MSDNC', // Derogatory for MSNBC
		'Clinton News Network', // Derogatory for CNN
		'State Run Media',
		'Propaganda Network',
		'Conservative Echo Chamber',
		'Liberal Echo Chamber',

		// Digital/Social Media News
		'Substack',
		'Medium',
		'Twitter News',
		'X News',
		'Facebook News',
		'Meta News',
		'Apple News',
		'Google News',
		'YouTube News',
		'NewsNation',
		'The Young Turks',
		'TYT Network',
		'InfoWars',
		'Daily Wire',
		'The Epoch Times',
		'Breaking Points',
		'Rising',
		'The Hill Rising',
		'Ground News',
		'NewsGuard',
		'Media Bias Fact Check',

		// News Radio
		'Talk Radio',
		'Conservative Talk Radio',
		'Liberal Talk Radio',
		'Progressive Talk Radio',
		'Public Radio',
		'Sinclair Broadcasting',
		'iHeartRadio News',
		'Westwood One News',
		'CBS Radio News',
		'ABC Radio News',
		'Fox News Radio',
		'NPR News',

		// News Terms
		'Breaking News',
		'Special Report',
		'Exclusive',
		'Live Coverage',
		'Prime Time',
		'Cable News',
		'Network News',
		'Morning Show',
		'Evening News',
		'Sunday Shows',
		'Political Commentary',
		'Opinion Programming',
		'News Analysis',
		'Investigative Reporting',
		'Hit Piece',
		'Tabloid News',
		'Yellow Journalism',
		'Clickbait',
		'News Aggregator',
		'Wire Service',
		'News Wire',
		'News Bureau',
		'News Desk',
		'Newsroom',

		// Political Party
		'Democrat',
		'Democrats',
		'Democratic',
		'Republican',
		'Republicans',
		'GOP',
		'MAGA',
		'Never-Trumper',
		'Trumpism',
		'Trumpian',
		'Independent',
		'Independents',
		'Libertarian',
		'Libertarians',
		'Green Party',
		'Constitution Party',
		'Blue Dog Democrat',
		'Progressive Democrat',
		'Establishment Democrat',
		'Corporate Democrat',
		'RINO',
		'Tea Party',
		'Freedom Caucus',
		'Squad',
		'Democratic Socialist',
		'Moderate',
		'Moderates',
		'Centrist',
		'Centrists',
		'Bipartisan',
		'Partisan',
		'Swing voter',
		'Swing district',
		'Red state',
		'Blue state',
		'Purple state',
		'Battleground state',
		'Liberal elite',
		'Coastal elite',
		'Establishment',
		'Anti-establishment',
		'Grassroots',
		'Base',
		'Political base',
		'Super PAC',
		'Dark money',
		'Special interest',
		'Lobbyist',
		'Lobbying',
		'Think tank',
		'Populist',
		'Populism',
		'Neoconservative',
		'Neocon',
		'Paleoconservative',
		'Neoliberal',
		'Reaganite',
		'Reaganism',
		'Clintonite',
		'Berniecrat',
		'Progressive wing',
		'Conservative wing',
		'Moderate wing',
		'Hard left',
		'Hard right',
		'Far left',
		'Far right',
		'Alt-right',
		'Alt-left',
		'Radical left',
		'Radical right',
		'Center-left',
		'Center-right',
		'Left-wing',
		'Right-wing',
		'Third party',
		'Third way',
		'Deep state',
		'Shadow government',
		'Administrative state',
		'Bureaucrat',
		'Bureaucracy',
		'Career politician',
		'Political insider',
		'Political outsider',
		'Political dynasty',
		'Political elite',
		'Political class',
		'Political establishment',
		'Beltway',
		'Inside the Beltway',
		'Washington elite',
		'Swamp',
		'Drain the swamp',
		'Political machine',
		'Party line',
		'Party loyalty',
		'Party platform',
		'Primary challenger',
		'Incumbent',
		'Challenger',
		'Frontrunner',
		'Running mate',
		'Down ballot',
		'Split ticket',
		'Straight ticket',
		'Political donor',
		'Megadonor',
		'Small donor',
		'Bundler',
		'Super delegate',
		'Delegate',
		'Caucus',
		'Primary',
		'Open primary',
		'Closed primary',
		'Convention',
		'National convention',
		'Party chair',
		'Party leader',
		'Minority leader',
		'Majority leader',
		'Whip',
		'Speaker',
		'Minority whip',
		'Majority whip',
		'Campaign',
		'Campaigning',
		'Campaign trail',
		'Campaign finance',
		'War chest',
		'Political action committee',
		'PAC',
		'DNC',
		'RNC',
		'DCCC',
		'NRCC',
		'DSCC',
		'NRSC',
		'Blue wave',
		'Red wave',
		'Political revolution',
		'Political movement',
		'Grassroots movement',
		'Political coalition',
		'Voter bloc',
		'Base voter',
		'Swing voter',
		'Undecided voter',
		'Low-information voter',
		'High-information voter',
		'Single-issue voter',
		'Values voter',
		'Silent majority',
		'Moral majority',
		'Political mandate',
		'Political capital',
		'Political liability',
		'Political suicide',
		'Political theater',
		'Political circus',
		'Political witch hunt',
		'Political hit job',
		'Opposition research',
		'Oppo',
		'October surprise',
		'Spin',
		'Spin doctor',
		'Message discipline',
		'Talking points',
		'Sound bite',
		'Gaffe',
		'Dog whistle',
		'Political correctness',
		'Cancel culture',
		'Culture war',
		'Identity politics',
		'Class warfare',
		'Political polarization',
		'Gridlock',
		'Obstructionism',
		'Filibuster',
		'Nuclear option',
		'Packing the court',
		'Court packing',

		// Federal Government Branches
		'Senate',
		'Senator',
		'Senators',
		'Congress',
		'Congressional',
		'Congressman',
		'Congresswoman',
		'Congressperson',
		'House of Representatives',
		'Representative',
		'House Speaker',
		'Speaker of the House',
		'Executive Branch',
		'Executive Order',
		'Executive Action',
		'Executive Power',
		'Judicial Branch',
		'Supreme Court',
		'SCOTUS',
		'Federal Court',
		'District Court',
		'Appeals Court',
		'Circuit Court',
		'Federal Judge',
		'Chief Justice',
		'Associate Justice',

		// Legislative Terms
		'Legislature',
		'Legislative',
		'Bill',
		'Amendment',
		'Resolution',
		'Filibuster',
		'Cloture',
		'Majority Leader',
		'Minority Leader',
		'Whip',
		'Committee',
		'Subcommittee',
		'Oversight Committee',
		'Select Committee',
		'Joint Committee',
		'Hearing',
		'Markup',
		'Floor Vote',
		'Voice Vote',
		'Roll Call',
		'Quorum',
		'Conference Committee',
		'Reconciliation',
		'Omnibus',
		'Continuing Resolution',
		'CR',
		'Appropriations',
		'Authorization',

		// Executive Branch
		'President',
		'Presidential',
		'Vice President',
		'VP',
		'POTUS',
		'VPOTUS',
		'Administration',
		'Cabinet',
		'Secretary',
		'Department',
		'Agency',
		'Bureau',
		'White House',
		'Oval Office',
		'West Wing',
		'East Wing',
		'First Lady',
		'First Gentleman',
		'Chief of Staff',
		'Press Secretary',
		'National Security Advisor',
		'Director of National Intelligence',
		'DNI',
		'Joint Chiefs',
		'Pentagon',

		// Federal Departments
		'State Department',
		'Treasury Department',
		'Defense Department',
		'DOD',
		'Justice Department',
		'DOJ',
		'Interior Department',
		'Agriculture Department',
		'USDA',
		'Commerce Department',
		'Labor Department',
		'Health and Human Services',
		'HHS',
		'Housing and Urban Development',
		'HUD',
		'Transportation Department',
		'DOT',
		'Energy Department',
		'Education Department',
		'Veterans Affairs',
		'VA',
		'Homeland Security',
		'DHS',

		// Federal Agencies
		'FBI',
		'CIA',
		'NSA',
		'EPA',
		'FDA',
		'FCC',
		'SEC',
		'FTC',
		'IRS',
		'TSA',
		'ICE',
		'CBP',
		'FEMA',
		'NASA',
		'NIH',
		'CDC',
		'Federal Reserve',
		'Fed',

		// State Government
		'Governor',
		'State Legislature',
		'State Senate',
		'State House',
		'State Assembly',
		'State Senator',
		'State Representative',
		'State Delegate',
		'Lieutenant Governor',
		'State Attorney General',
		'AG',
		'Secretary of State',
		'State Supreme Court',
		'State Court',

		// Local Government
		'Mayor',
		'City Council',
		'County Commission',
		'Commissioner',
		'Supervisor',
		'Alderman',
		'Municipal',
		'Township',
		'Borough',
		'District',
		'Precinct',

		// Electoral Terms
		'Election',
		'Primary',
		'Caucus',
		'Convention',
		'Campaign',
		'Ballot',
		'Vote',
		'Voter',
		'Polling',
		'Precinct',
		'District',
		'Gerrymandering',
		'Redistricting',
		'Reapportionment',
		'Electoral College',
		'Elector',

		// Political Process
		'Legislation',
		'Regulation',
		'Policy',
		'Statute',
		'Law',
		'Ruling',
		'Decision',
		'Precedent',
		'Oversight',
		'Investigation',
		'Subpoena',
		'Testimony',
		'Witness',
		'Confirmation',
		'Nomination',
		'Appointment',
		'Impeachment',
		'Censure',
		'Veto',
		'Override',
		'Treaty',
		'Executive Agreement',
		'Declaration',
		'Proclamation',

		// Constitutional Terms
		'Constitution',
		'Constitutional',
		'Amendment',
		'Bill of Rights',
		'Article',
		'Section',
		'Clause',
		'Power',
		'Authority',
		'Jurisdiction',
		'States Rights',
		'Federal Rights',
		'Civil Rights',
		'Due Process',
		'Equal Protection',
		'Commerce Clause',
		'Necessary and Proper Clause',
		'Supremacy Clause',


		// Politically Charged words
		'abortion',
		'abortions',
		'aborting',
		'aborted',
		'DEI',
		'socialist',
		'socialism',
		'socialists',
		'communist',
		'communism',
		'communists',
		'fascist',
		'fascism',
		'fascists',
		'fascistic',
		'nationalist',
		'nationalism',
		'nationalists',
		'capitalist',
		'capitalism',
		'capitalists',
		'marxist',
		'marxism',
		'marxists',
		'diversity',
		'diverse',
		'diversifying',
		'equity',
		'equitable',
		'inclusion',
		'inclusive',
		'including',
		'progressive',
		'progressives',
		'progressing',
		'conservative',
		'conservatives',
		'conservatism',
		'radical',
		'radicals',
		'radicalizing',
		'radicalized',
		'radicalization',
		'liberal',
		'liberals',
		'liberalism',
		'leftist',
		'leftists',
		'rightist',
		'rightists',
		'right-wing',
		'left-wing',
		'woke',
		'wokeness',
		'patriarchy',
		'patriarchal',
		'transgender',
		'trans',
		'transitioning',
		'transitioned',
		'pronoun',
		'pronouns',
		'immigrant',
		'immigrants',
		'immigration',
		'immigrating',
		'deport',
		'deporting',
		'deportation',
		'deported',
		'border',
		'borders',
		'refugee',
		'refugees',
		'welfare',
		'privilege',
		'privileged',
		'racist',
		'racism',
		'racists',
		'racial',
		'sexist',
		'sexism',
		'sexists',
		'misogynist',
		'misogyny',
		'misogynistic',
		'protest',
		'protests',
		'protesting',
		'protester',
		'protesters',
		'revolution',
		'revolutionary',
		'revolutionaries',
		'censor',
		'censoring',
		'censorship',
		'censored',
		'indoctrinate',
		'indoctrinating',
		'indoctrination',
		'indoctrinated',
		'propaganda',
		'propagandist',
		'colonialism',
		'colonialist',
		'colonizing',
		'colonized',
		'colonizer',
		'reparation',
		'reparations',
		'extremist',
		'extremism',
		'extremists',
		'terrorist',
		'terrorism',
		'terrorists',
		'terroristic',
		'activist',
		'activism',
		'activists',
		'discriminate',
		'discrimination',
		'discriminating',
		'discriminated',
		'feminist',
		'feminism',
		'feminists',
		'patriot',
		'patriots',
		'patriotic',
		'nationalism',
		'nationalist',
		'nationalists',
		'anarchist',
		'anarchy',
		'anarchists',
		'anarchistic',
		'militia',
		'militias',
		'militiant',
		'supremacist',
		'supremacy',
		'supremacists',
		'populist',
		'populism',
		'populists',
		'establishment',
		'anti-establishment',
		'elite',
		'elites',
		'elitism',
		'elitist',
		'oppression',
		'oppressing',
		'oppressed',
		'oppressive',
		'authoritarian',
		'authoritarianism',
		'libertarian',
		'libertarianism',
		'totalitarian',
		'totalitarianism',
		'resistance',
		'resisting',
		'resistant',
		'resist',
		'ideology',
		'ideological',
		'ideologies',
		'polarization',
		'polarizing',
		'polarized',
		'misinformation',
		'disinformation',
		'conspiracy',
		'conspiracies',
		'conspirator',
		'conspiracy theorist',
		'dissent',
		'dissenting',
		'dissenter',
		'dissidence',
		'dissident',
		'insurrection',
		'insurrectionist',
		'sedition',
		'seditious',
		'xenophobia',
		'xenophobic',
		'homophobia',
		'homophobic',
		'islamophobia',
		'islamophobic',
		'antisemitism',
		'antisemitic',
		'segregation',
		'segregating',
		'segregated',
		'segregationist',
		'assimilation',
		'assimilating',
		'assimilated',
		'white privilege',
		'white supremacy',
		'critical race theory',
		'CRT',
		'politically correct',
		'political correctness',
		'cancel culture',
		'cancelled',
		'cancelling',
		'triggered',
		'triggering',
		'snowflake',
		'microaggression',
		'microaggressions',
		'cultural appropriation',
		'appropriating',
		'appropriated',
		'safe space',
		'mansplaining',
		'mansplain',
		'toxic masculinity',
		'patriarch',
		'patriarchal',
		'gender fluid',
		'non-binary',
		'cisgender',
		'heteronormative',
		'marginalized',
		'marginalizing',
		'minorites',
		'minority',
		'white fragility',
		'systemic racism',
		'institutional racism',
		'voter fraud',
		'election fraud',
		'voter suppression',
		'gerrymandering',
		'gerrymandered',
		'deep state',
		'swamp',
		'drain the swamp',
		'fake news',
		'mainstream media',
		'MSM',
		'alternative facts',
		'culture war',
		'identity politics',
		'political dynasty',
		'establishment',
		'globalist',
		'globalism',
		'nationalist',
		'neocon',
		'neoconservative',
		'neoliberal',
		'radical left',
		'radical right',
		'far-left',
		'far-right',
		'alt-right',
		'antifa',
		'anti-fascist',
		'surveillance state',
		'police state',
		'defund',
		'defunding',
		'pro-life',
		'pro-choice',
		'gun control',
		'gun rights',
		'second amendment',
		'constitutional carry',
		'climate change denier',
		'climate crisis',
		'green new deal',
		'environmental justice',
		'fossil fuels',
		'big tech',
		'big pharma',
		'big government',
		'socialist agenda',
		'liberal agenda',
		'conservative agenda',
		'radical agenda',
		'illegal alien',
		'illegal immigrant',
		'undocumented',
		'sanctuary city',
		'build the wall',
		'open borders',
		'border crisis',
		'border security',
		'amnesty',
		'deportation',
		'chain migration',
		'birthright citizenship',
		'welfare state',
		'entitlements',
		'affirmative action',
		'reverse discrimination',
		'quotas',
		'political bias',
		'biased',
		'rigged',
		'rigging',
		'corruption',
		'corrupt',
		'scandal',
		'climate',
		'climate change',
		'controversial',
		'regime',
		'regime change',
		'warmonger',
		'warmongering',
		'imperialist',
		'imperialism',
		'colonizer',
		'neoconservative',
		'neoliberal',
		'class warfare',
		'wealth redistribution',
		'redistribution',
		'big government',
		'small government',
		'states rights',
		'federal overreach',
		'overregulation',
		'deregulation',

		// Countries
		'China',
		'Chinese',
		'Communist China',
		'Russia',
		'Russian',
		'Russians',
		'Ukraine',
		'Ukrainian',
		'Israel',
		'Israeli',
		'Israelis',
		'Palestine',
		'Palestinian',
		'Palestinians',
		'Iran',
		'Iranian',
		'Iranians',
		'North Korea',
		'North Korean',
		'South Korea',
		'South Korean',
		'Afghanistan',
		'Afghan',
		'Afghans',
		'Iraq',
		'Iraqi',
		'Syria',
		'Syrian',
		'Syrians',
		'Saudi Arabia',
		'Saudi',
		'Saudis',
		'Venezuela',
		'Venezuelan',
		'Cuba',
		'Cuban',
		'Cubans',
		'Mexico',
		'Mexican',
		'Mexicans',
		'Taiwan',
		'Taiwanese',
		'Vietnam',
		'Vietnamese',
		'Pakistan',
		'Pakistani',
		'India',
		'Indian',
		'Yemen',
		'Yemeni',
		'Turkey',
		'Turkish',
		'Egypt',
		'Egyptian',
		'Libya',
		'Libyan',
		'Lebanon',
		'Lebanese',
		'Myanmar',
		'Burmese',
		'Belarus',
		'Belarusian',
		'Nicaragua',
		'Nicaraguan',
		'El Salvador',
		'Salvadoran',
		'Honduras',
		'Honduran',
		'Guatemala',
		'Guatemalan',
		'Haiti',
		'Haitian',
		'Somalia',
		'Somali',
		'Sudan',
		'Sudanese',
		'Ethiopia',
		'Ethiopian',
		'Congo',
		'Congolese',
		'Nigeria',
		'Nigerian',
		'Qatar',
		'Qatari',
		'UAE',
		'Emirati',
		'Kuwait',
		'Kuwaiti',
		'Azerbaijan',
		'Azerbaijani',
		'Armenia',
		'Armenian',
		'Georgia',
		'Georgian',
		'Kazakhstan',
		'Kazakh',
		'Uzbekistan',
		'Uzbek',
		'Kyrgyzstan',
		'Kyrgyz',
		'Tajikistan',
		'Tajik',
		'Turkmenistan',
		'Turkmen',
		'Cambodia',
		'Cambodian',
		'Laos',
		'Laotian',
		'Philippines',
		'Filipino',
		'Indonesia',
		'Indonesian',
		'Malaysia',
		'Malaysian',
		'Thailand',
		'Thai',
		'Singapore',
		'Singaporean',
		'Tibet',
		'Tibetan',
		'Xinjiang',
		'Uyghur',
		'Hong Kong',
		'Hong Konger',
		'Kosovo',
		'Kosovar',
		'Serbia',
		'Serbian',
		'Poland',
		'Polish',
		'Hungary',
		'Hungarian',
		'Romania',
		'Romanian',
		'Moldova',
		'Moldovan',
		'Colombia',
		'Colombian',
		'Brazil',
		'Brazilian',
		'Argentina',
		'Argentinian',
		'Chile',
		'Chilean',
		'Peru',
		'Peruvian',
		'Ecuador',
		'Ecuadorian',
		'Bolivia',

		// Political Figures

		'Donald Trump',
		'Trump',
		'DJT',
		'The Donald',
		'Joe Biden',
		'Joseph Biden',
		'Biden',
		'POTUS',
		'Joey B',
		'Vladimir Putin',
		'Putin',
		'Vladmir Putin',
		'VVP',
		'Volodymyr Zelenskyy',
		'Zelenskyy',
		'Zelensky',
		'Володимир Зеленський',
		'Zelenskyi',
		'Xi Jinping',
		'Xi',
		'President Xi',
		'Rishi Sunak',
		'Sunak',
		'Rich Sunak',
		'Benjamin Netanyahu',
		'Netanyahu',
		'Bibi',
		'Kamala Harris',
		'VP Harris',
		'Kamala D. Harris',
		'Emmanuel Macron',
		'Macron',
		'President Macron',
		'Olaf Scholz',
		'Scholz',
		'Ron DeSantis',
		'DeSantis',
		'Ronald DeSantis',
		'Narendra Modi',
		'Modi',
		'NaMo',
		'Justin Trudeau',
		'Trudeau',
		'JT',
		'Alexandria Ocasio-Cortez',
		'AOC',
		'Ocasio-Cortez',
		'Tucker Carlson',
		'Carlson',
		'Tucker',
		'Nikki Haley',
		'Nimrata Haley',
		'Nimrata Nikki Haley',
		'Mike Johnson',
		'Michael Johnson',
		'Chuck Schumer',
		'Charles Schumer',
		'Charles E. Schumer',
		'Mitch McConnell',
		'Mitchell McConnell',
		'Robert F. Kennedy Jr.',
		'RFK Jr.',
		'Bobby Kennedy Jr.',
		'Viktor Orbán',
		'Orban',
		'Viktor Orban',
		'Marine Le Pen',
		'Le Pen',
		'Kevin McCarthy',
		'McCarthy',
		'Hakeem Jeffries',
		'Jeffries',
		'Ursula von der Leyen',
		'VDL',
		'von der Leyen',
		'Giorgia Meloni',
		'Meloni',
		'Jens Stoltenberg',
		'Stoltenberg',
		'Kim Jong-un',
		'Kim Jong Un',
		'Chairman Kim',
		'Mohammed bin Salman',
		'MBS',
		'Recep Tayyip Erdogan',
		'Erdogan',
		'RTE',
		'Erdoğan',
		'Lula da Silva',
		'Lula',
		'Luiz Inácio Lula da Silva',
		'Javier Milei',
		'Milei',
		'Pete Buttigieg',
		'Mayor Pete',
		'Buttigieg',
		'Marjorie Taylor Greene',
		'MTG',
		'Ron Paul',
		'Ronald Paul',
		'Gabriel Boric',
		'Boric',
		'Yoon Suk-yeol',
		'Yoon',
		'Anthony Albanese',
		'Albo',
		'Albanese',
		'Lauren Boebert',
		'Boebert',
		'Matt Gaetz',
		'Matthew Gaetz',
		'Ted Cruz',
		'Rafael Edward Cruz',
		'Josh Hawley',
		'Joshua Hawley',
		'Jim Jordan',
		'James Jordan',
		'Nancy Pelosi',
		'Pelosi',
		'Hillary Clinton',
		'HRC',
		'Hillary Rodham Clinton',
		'Michelle Obama',
		'Mrs. Obama',
		'Bernie Sanders',
		'Bernard Sanders',
		'Elizabeth Warren',
		'Liz Warren',
		'Rand Paul',
		'Randal Paul',
		'Mike Pence',
		'Michael Pence',
		'Michael Richard Pence',
		'Tim Scott',
		'Timothy Scott',
		'Vivek Ramaswamy',
		'Ramaswamy',
		'George Soros',
		'György Schwartz',
		'Keir Starmer',
		'Sir Keir Starmer',
		'Humza Yousaf',
		'Yousaf',
		'Leo Varadkar',
		'Varadkar',
		'Pedro Sánchez',
		'Sanchez',
		'Alexander Lukashenko',
		'Lukashenko',
		'Nicolás Maduro',
		'Maduro',
		'Daniel Ortega',
		'Ortega',
		'Miguel Díaz-Canel',
		'Diaz-Canel',
		'Ebrahim Raisi',
		'Raisi',
		'Nayib Bukele',
		'Bukele',
		'Gustavo Petro',
		'Petro',
		'Xiomara Castro',
		'Castro',
		'Alberto Fernández',
		'Fernandez',
		'Andres Manuel López Obrador',
		'AMLO',
		'López Obrador',
		'William Ruto',
		'Ruto',
		'Cyril Ramaphosa',
		'Ramaphosa',
		'Bola Tinubu',
		'Tinubu',
		'Abdel Fattah el-Sisi',
		'Sisi',
		'Mohammed bin Zayed',
		'MBZ',
		'Yair Lapid',
		'Lapid',
		'Benny Gantz',
		'Gantz',
		'Antony Blinken',
		'Tony Blinken',
		'Janet Yellen',
		'Yellen',
		'Lloyd Austin',
		'Secretary Austin',
		'Merrick Garland',
		'AG Garland',
		'Jack Smith',
		'Special Counsel Smith',
		'Alvin Bragg',
		'DA Bragg',
		'Fani Willis',
		'DA Willis',
		'John Fetterman',
		'Fetterman',
		'J.D. Vance',
		'JD Vance',
		'James David Vance',
		'Tommy Tuberville',
		'Coach Tuberville',
		'Joe Manchin',
		'Joseph Manchin',
		'Kyrsten Sinema',
		'Sinema',
		'Susan Collins',
		'Collins',
		'Lisa Murkowski',
		'Murkowski',
		'Mitt Romney',
		'Willard Romney',
		'Willard Mitt Romney',
		'Ilhan Omar',
		'Omar',
		'Rashida Tlaib',
		'Tlaib',
		'Adam Schiff',
		'Schiff',
		'Jamie Raskin',
		'Raskin',
		'Liz Cheney',
		'Elizabeth Cheney',
		'Letitia James',
		'Tish James',
		'Ron Wyden',
		'Ronald Wyden',
		'Marco Rubio',
		'Rubio',
		'Tom Cotton',
		'Thomas Cotton',
		'Gavin Newsom',
		'Newsom',
		'Greg Abbott',
		'Abbott',
		'Gretchen Whitmer',
		'Whitmer',
		'Kari Lake',
		'Lake',
		'Brian Kemp',
		'Bill Gates',

        // Handle common misspellings
        'trumph',
        'trmp',
        'trmup',
        'drumpf',
        'drumph',
        'elan',
        'elong',
        'elonge',
        'elan mask',
        'elon mask',
        'elon must',
        'elon musket',
        'elon mosque',
        'eelon',
        'ilon',
        'elonn',
        'musc',
        'mosk',
        'mousk',
        'mussk',
        'musque',
        'elun',
        'eloln',
        'alon',
        'eyon',
        'elon/musk',
        'e/musk',
        'musk/elon',
        'mr.musk',
        'mr.elon',
        'sir elon',
        'lord elon',
        'papa elon',
        'daddy elon',
        'doneld',
        'donnald',
        'donal',
        'president',
        'precedent',
        'presidant',
        'preident',
        'presedent',
        'preisdent'
    ];